FROM ubuntu:22.04
RUN apt update && apt install -y gcc g++ libseccomp-dev curl && rm -rf /var/lib/apt/lists
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="$PATH:/root/.cargo/bin"

CMD ["cargo", "build", "--release"]